name: TimeStopper
main: RevivalPMMP\TimeStopper\TimeStopper
version: 1.0.1
api:
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
load: POSTWORLD
authors:
- "RevivalPMMP"
- "95CivicSi"
- "jasonwynn10"
description: "Sets and stops server time on server restarts."