name: TimeStopper
main: RevivalPMMP\TimeStopper\TimeStopper
version: 1.0.0
api:
- 3.0.0-ALPHA10
load: POSTWORLD
authors:
- "RevivalPMMP"
- "95CivicSi"
- "jasonwynn10"
description: "Restores server settings on restarts (eg time stopped)."